### ISSUE TITLE
Keep getting alot of unidentified errors

### ISSUE THREAD

**Issue by SleekZ** [beans42/R6-external-esp-v2#1]

**Comment by SleekZ** [comment]
[Errors ](https://cdn.discordapp.com/attachments/529956368547971090/637649502551015434/unknown.png)

**Comment by ebrahim37** [comment]
If you did the slightest bit of research you could have found our that you need to download directx sdk and add it to vc++ directories.

**Comment by SleekZ** [comment]
perhaps you could be slightly bothered to put it into the readme

**Comment by ebrahim37** [comment]
> perhaps you could be slightly bothered to put it into the readme

All you had to do was google the header file name. But I’ll add it to description anyway.
